import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className+' flex flex-col'}>
        <nav>
          <ul className="flex">
            <NavLi>
              <Link href="/">Home</Link>
            </NavLi>
            <NavLi>
              <Link href="/dashboard">Dashboard</Link>
            </NavLi>
          </ul>
        </nav>
        <div className='h-full w-full'>
          {children}
        </div>
      </body>
    </html>
  )
}

function NavLi({children}: {children: ReactNode}) {
  return <li className="p-2">{children}</li>
}
